[package]
name = "flappybird"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bevy = "0.13.0"
bevy-inspector-egui = { version = "0.23.2", optional = true }
bevy_embedded_assets = "0.10.0"
